<?php

namespace AppBundle\Repository;

/**
 * commandeParProducteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class commandeParProducteurRepository extends \Doctrine\ORM\EntityRepository
{
}
