<?php

namespace AppBundle\Repository;

/**
 * EtatLivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtatLivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
