<?php

namespace AppBundle\Repository;

/**
 * ProducteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducteurRepository extends \Doctrine\ORM\EntityRepository
{
}
