<?php

namespace AppBundle\Repository;

/**
 * produitsPanierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitsPanierRepository extends \Doctrine\ORM\EntityRepository
{
}
