<?php

namespace AppBundle\Repository;

/**
 * produitsCommandeParProducteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class produitsCommandeParProducteurRepository extends \Doctrine\ORM\EntityRepository
{
}
